### PR TITLE
Restore wash -C flag to original behaviour

### PR DESCRIPTION
**Pull request by rofl0r**
see #106

### CODE REVIEW

**Comment by blshkv** [comment]
This is still a bit confusing. Is it possible to specify both -C and -F ?
If not, shouldn't it be --announce-fcs={y|n} ?

**Comment by rofl0r** [comment]
right now the behavior is: whatever comes last takes precedence.
that is similar to e.g. a C-compiler, where you can also specify -fomit-frame-pointer and -fno-omit-frame-pointer.
also i suppose ppl who can read will not mix up the 2 together.

**Comment by blshkv** [comment]
Just by reading names I'm getting an impression that "--announce-fcs" is something that "sends" fcs and "--ignore-fcs" has to "receive" fcs.

But anyway, it would be good to add "OR" condition. Is there such option in getopt?

**Comment by blshkv** [comment]
Actually, I think it would be better to have just one of parameters with clear {y|n} choice and documented <default> value

**Comment by rofl0r** [comment]
getopt is a quite horrible interface - i don't use it in any of my own projects.
so: dunno. and i also don't wanna spend more time on this. imo this solves the issue at hand, while maintaining the ability to use the new functionality.
so my stance is: let's see if this get merged, and if you really want that to be changed, come up with a new PR then.

**Comment by blshkv** [comment]
Honestly, I don't see any reason for the new -F flag. It is a default action and the tool works the same with or without it.

**Comment by rofl0r** [comment]
even if it is the default (it probably was with flatr0ze entire patch), the option explicitly enables the functionality. so it will enable it even if the default is changed. it doesn't hurt to have it there.
that said, i will now wait what @kcdtv or @soxrok2212 or @t6x have to say and if it will be merged or not.

**Comment by kcdtv** [comment]
I do not have time now (untill day 29) to explain you why and i need to check a couple of stuff with some chipset  but the change shouldn't be reversed, it is a good one, it should have just be documented correctly.
Enjoy your hollidays and we will pseak about it in the end of this year

**Comment by kcdtv** [comment]
Hi everybody!
  Let me explain what happened with -C option
Before the change it was necessary to use this option with all Ralink USB chipsets in order to avoid 
`[!] Found packet with bad FCS, skipping...`
in loop.
  Now we do not need to use the -C option with any chipset.
  This might break retro-compatibility with wifite... but might fix compatibility with other scripts that did not use the -C option with Ralink chipset.
  The point here is to make wash as much convenient as possible for the users... that uses wash.  
  This change might be clumsy and not commented correctly but it is at the end of the day a good change as we do not have to take care anymore about the chipset we use when we launch wash.
  I think that we should simply deprecate and abandon the -C option as it is not required anymore and this situation of "changing meaning" is confusing and unnecessary (as pointed out  **blshkv** )  
  I think that is the good direction to take, I am sorry because you did a good work, but as pragmatic user I sincerely think that it is better to get rid off this option now that is not required anymore.

**Comment by blshkv** [comment]
Ok, it looks like my patch works the best:
https://github.com/pentoo/pentoo-overlay/blob/master/net-wireless/reaver-wps-fork-t6x/files/0006-announce-fcs.patch

In short: the "old" parameter -C does nothing, the new -F inherit its "new" behaviour, i.e. enables announcement of fcs.

it makes it compatible with old tools (if they still call it with -C) and does not break any functionality.

**Comment by rofl0r** [comment]
@kcdtv pushed  a new commit addressing your comments. ^

**Comment by soxrok2212** [comment]
The problem here is we should not assume compatibility with older scripts. This will only hold back development. If older scripts want to keep working, they need to be updated to work with the tools actually doing the work instead, not the other way around. Reaver is a dependency of scripts, scripts are not a dependency of Reaver. I think -C is pointless and should be enabled by default.

**Comment by rofl0r** [comment]
@soxrok2212: yep, my patch does just that. it enables -C functionality by default, and makes the flag a no-op (rather than raising an error about "invalid flag"). i think that behavior is much nicer since wifite can not know whether the user has reaver vanilla (-C needed here) or t6x fork.

**Comment by kcdtv** [comment]
> The problem here is we should not assume compatibility with older scripts. This will only hold back development. 


  I fully agree :+1: 
I think that we are loosing focus here and I do not see the point to have now two options -C and -F  
when we can simply get rid of -C and have a correct behavior with all Chipsets.

**Comment by blshkv** [comment]
Fine with me too.  As long as it is not a reversed meaning.

**Comment by rofl0r** [comment]
so you're fine with -C throwing an error instead of just being ignored ? i doubt that will be good for the wifite folks who try to make their product work with legacy and t6x reaver.
but anyway, i'm not going to fight over this since i actually just wanted to be helpful.

**Comment by rofl0r** [comment]
regarding the other changes of that suspicious commit i reverted: i have the strong feeling that that commit introduced a bug where either p1/2_index get erroneusly incremented or just the progress display even when a pin try was aborted due to an error. so i'm still in favor to undo that commit and then over time see if that fixed the issue i'm refering to.
in case you dont know what i mean: imagine you have a bad connection to a far away AP, so reaver tries to connect to it but it never succeeds to actually submit the pin. but even though a pin is actually never tried, the counter goes up  and tells you something like "0.3 % completed, (30s/try), ETA 12:20:01"

**Comment by blshkv** [comment]
I'm fine dropping it because an error would probably break a calling script and users would know that something wrong (at least).  The two previous projects are dead anyway so there is no point looking at them.

I mean, I don't really see how would it "hold back development". This clearly BS.
Take nmap, for example. It is a way more popular tool and they have to keep TWO flags -P0 and -PN (the new one is -Pn) to be compatible with your own previous versions. But hey, it's your project. It does not have proper DLC (and no releases). You are free to break it as you want. :smiley:

**Comment by soxrok2212** [comment]
> i doubt that will be good for the wifite folks who try to make their product work with legacy and t6x reaver.

Well  what is the benefit of having Reaver 1.4 support?

**Comment by rofl0r** [comment]
well, some distros, for example openwrt still use reaver 1.4, mostly because they have a number of custom patches (such as big-endian support) that would be quite hard to forward port to t6x fork, and because there are no proper releases here, because the maintainers here were in the past not very responsive ( e.g. https://github.com/t6x/reaver-wps-fork-t6x/issues/66 ), and maybe because they fear that more bugs have been introduced than fixed. :)
so i can kinda understand that wifite wants to support both versions. and leaving the -C option there as a no-op costs as nothing, apart from 2 added lines of code.

**Comment by kcdtv** [comment]
Happy 2017 to everybody! 


> Yes it is not particularly a good idea to ignore warnings, but honestly, at least in my findings, not too many people use Ralink. And if they do, it still works just fine.


  It is simply beacuse **you can't**. 
Association and wps flow are so dirty that you won't even be able to do a pixiedust attack.
  Bully works a bit better (not great but you will be able to do some brute force using pauses)
  So we are speaking about chipset that cannot be used with reaver. 


> so i can kinda understand that wifite wants to support both versions. and leaving the -C 


Wifite is not under development since years and does not care about that at all... 
The last change was quickly introduced to support pixiewps in may 2015... [https://github.com/derv82/wifite](url). The change was introduced late, I thought that the Kali crew would have take the AanarchyY branch who was the first to introduce pixiewps support in wifite.
 But the kali crew waited for derv82 to do it.
 Since this last change (may 2015) there is absolutely nothing going on in this code... 
   The project is here for ages (originally designed for backtrack) and the author has not any more interest in it. 
Fair enough, no problems: There are hundreds of script to guide you in your wps attack that are under development. 

  But again: Why should we even speak about wifite here? 
It is not a hacking tool: It is a wrapper that automate everything. 
  It has no pedagogical interest (you do not learn wifi hacking using wifite ) 
  It is of course useless compared to command line (no one that knows wifi hacking use wifite to audit a network)
It is a very nice piece of code but it is what it is
 The wrapper has to follow the tools that it uses, not the other way round.

  At the end of day, having a tool with two useless options doesn't make sense.
  Evolution is about leaving things behinds when it makes sense
  I have now no error with wash minimal sentence and I do not need to care about my chipset and to use or not the -C option (or -F) 
  That's pretty good and has been like this since one year... 
  The mistake here was in the lack of documentation and to leave the **-C** option active with an inverted meaning

**Comment by blshkv** [comment]
Quick comment: wifite2 brach  is very actulive

**Comment by kcdtv** [comment]
Program is distro independent as reaver 1.4 was. 
  Nothing changed
It is not an only *.deb released and can be installed in many distributions following the instructions given. 


>  and they are waiting for your final decision,


They should not use the -C tag with wash, it is not necessary, they can change their wash command line.

**Comment by rofl0r** [comment]
there, i removed -C ^

**Comment by kcdtv** [comment]
We can drop **-F**  too... I can do it tonight-later if you don't have time to do it

**Comment by rofl0r** [comment]
no problem, done.

**Comment by kcdtv** [comment]
I tested with Ralink and Atheros: Everything went fine with the recommended minimal syntax for wash. 
  We can forget for ever about `[!] Found packet with bad FCS, skipping..`
     Nice!

**Comment by rofl0r** [comment]
sweet! thanks for merging.

**Pull request merged**
