### PR TITLE
FAKE NACK support & bug fix.

### PR DESCRIPTION
**Pull request by KokoSoft**
Add:
* Display of reason code for NACK
* Detection of changing the reason code for NACK.
* Detection of FAKE NACK after M4, when cracking 2nd pin half.
* Ability to definie the reason code for NACK used in FAKE NACK.
* Sleep after detection of FAKE NACK.
* In exhaustive mode, restart attack when pin was not found.

Fixs:
* Don't increment p2_index, when received NACK after sending M4.
* Quiting after advice all possible 1st pin halfs.
* Auto exhaustive attack.
* Quit after num pin attempts (-g).

### CODE REVIEW

**Comment by kcdtv** [comment]
Hello there! 
Nice && Great Job ! :+1:
This deserves a merge...  Doesn't it guys? :smile_cat:
I have no time to test it today so i will not do the merge unilaterally by myself...  but it looks very good and you have my full blessing to do  (sox or aanarchy if you are around... or t6x,.. long time not seen you bro'... hope everything is fine....)
I assume that p1 does not rise either when a fake M4 is detected or does it? 
@ Kobosoft
I don't know if that very polite/ correct or the way to ask about this but I am trying to understand why/how brute force is broken by indexes count inversion when using -p option... Do you have any queue about that? ( [https://github.com/t6x/reaver-wps-fork-t6x/issues/50](url) )

thanks again Kobosoft, take care

**Comment by soxrok2212** [comment]
Just need to do a bit of code review and testing... should merge soon 👍

**Comment by soxrok2212** [comment]
@kcdtv are you able to test? Currently don't have any WPS enabled devices.

**Comment by aanarchyy** [comment]
So far this looks really nice, I will see if i can get to testing this later on tonight.
 Very nice work!

**Comment by kcdtv** [comment]
well, not really neither, i am at my grand ma place untill friday....  with no internet just 4G... than at my parents where i have a single router (their box) -  i can try friday... and i will be back in barcelona with all my devices at the end of the month.... there i have some acess point which could be used, i guess that have some fake "M4" behaviour
to be honnest as i don't do "C" i am not 100% sure about what the code patches are realy about and about the issue solved, I guess it is a behaviour that i found on some zte router that say that first half is good whatever PIN you send and make brute force impossible...
maybe tomorow night (EU) i can try to vist some people to try... i'll write you a mail sox to speak about that more directly _ maybe we could hang wuth gmail if you are around

**Comment by wiire** [comment]
@KokoSoft 
Judging by the code, a "fake NACK" is a NACK with reason code **0x05** sent by the Access Point when it doesn't accept any more WPS transactions but it doesn't report the **AP locked setup** flag. Am I correct?

Also Bully has a _Detect WPS lockouts unreported by AP_ feauture but I assume is something different. Could you tell us a bit more?

Thank you.

**Comment by KokoSoft** [comment]
Fake NACK occurs when you already know the first part of PIN and the router anser is NACK after sending M4. While breaking the second part of the code, increase the index **ONLY **if you receive NACK after sending M6. The error code used in the NACK depends on the device manufacturer. 
In my case the code was usually 0x1003 and 0x1005 when the router was blocked (FAKE NACK)

**Comment by soxrok2212** [comment]
Thanks for this! 👍 Merged.

**Pull request merged**
