### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by rofl0r**
basically just fixing horrible UB noticed by reading warnings...
am i the first one to build this on x86_64?
or is everybody using this on kali 32bit ?

### CODE REVIEW

**Comment by rofl0r** [comment]
(note: this is in preparation of a new feature i'm about to implement for wash)

**Comment by kcdtv** [comment]
Thanks (many) for your efforts.
I'll check that tonight and just let us some time to speak about it and check it before merging your pull request. 
I live in Europe, my mate does live in Amercia so sometime it can take us a couple of day to syncronise... Jet lag side effects...

> am i the first one to build this on x86_64?
or is everybody using this on kali 32bit ?

:smiley_cat:  No, we use 64bits OS and computers 
I can see the warnings and there have been several attempts to fix them, issues were opened, "fixes" made.
  Sometimes it looks like we want backward with some push... and we add to revert changes because the solution proposed were "cosmetic" and did not solved the issue, just silenced them.
  I was actually thinking about reverting more changes... But it is not easy to identify which ones... a lot of commits.
  pynegn zyxell is definitely one of this new features that created a lot of warnings.
  Comment is actually absolutely wrong, that's for example the bssid known for a single affected  device (Huawei HG56a)

> 20:2B:C1  30:87:30  5C:4C:A9  62:23:3D  62:3C:E4  62:3D:FF  62:53:D4  62:55:9C  62:6B:D3  62:7D:5E  62:96:BF  62:A8:E4  62:B6:86  62:C0:6F  62:C6:1F  62:C7:14  62:CB:A8  62:CD:BE  62:E8:7B  64:16:F0  6A:1D:67  6A:23:3D  6A:3D:FF  6A:53:D4  6A:55:9C  6A:6B:D3  6A:96:BF  6A:7D:5E  6A:A8:E4  6A:C0:6F  6A:C6:1F  6A:C7:14  6A:CB:A8  6A:CD:BE  6A:D1:5E  6A:D1:67  72:1D:67  72:23:3D  72:3C:E4  72:3D:FF  72:53:D4  72:55:9C  72:6B:D3  72:7D:5E  72:96:BF  72:A8:E4  72:C0:6F  72:C6:1F  72:C7:14  72:CB:A8  72:CD:BE  72:D1:5E  72E8:7B

 I will edit the comment correctly (and I will not put the bssid affected because it is insane, it is actually a wifi chipset issue, not a manufacturer one) This is my part of the job in this repo. 
  Coding is not my thing, C less... and a lot of contibutors did no show up anymore since... a long time. 
  So thank you very much for your efforts, the code needs it. 
 We check that asap to merge pull request asap. 
See you soon

**Comment by rofl0r** [comment]
> Sometimes it looks like we want backward with some push... and we add to revert
> changes because the solution proposed were "cosmetic" and did not solved the issue,
> just silenced them.
> I was actually thinking about reverting more changes... But it is not easy to identify which > ones... a lot of commits.

i understand.

> I tried but i still get the warning for the algorithm "Zao"
>>snprintf(pin, pin_len, "%08d", (default_pin * 10) + wps_checksum(default_pin));
>>^~
hmm it looks like you still are using your own branch, because my commit "fix UB in zaochunsheng algorithm" https://github.com/t6x/reaver-wps-fork-t6x/pull/89/commits/590e2efe99a09a3d329db3555c9597fd0f84ad42 completely removes the snprintf statement and doesnt use it anymore. it writes the 6 chars of interest into a new buffer and then just does scanf on it to put the result into an int.

**Comment by soxrok2212** [comment]
@rofl0r Thank you for these updates!

@kcdtv I went ahead and tested this and didn't have any compile warnings or errors (that I saw, looked quickly). I haven't been able to do much real testing at all so I'll leave that part to you.

`➜  src git:(rofl0r-fixes) ✗ make
(cd utils && make)
make[1]: Entering directory '/home/soxrok2212/reaver-wps-fork-t6x/src/utils'
  CC  common.c
ar crT libutils.a common.o
make[1]: Leaving directory '/home/soxrok2212/reaver-wps-fork-t6x/src/utils'
(cd tls && make)
make[1]: Entering directory '/home/soxrok2212/reaver-wps-fork-t6x/src/tls'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/soxrok2212/reaver-wps-fork-t6x/src/tls'
(cd crypto && make)
make[1]: Entering directory '/home/soxrok2212/reaver-wps-fork-t6x/src/crypto'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/soxrok2212/reaver-wps-fork-t6x/src/crypto'
(cd wps && make)
make[1]: Entering directory '/home/soxrok2212/reaver-wps-fork-t6x/src/wps'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/soxrok2212/reaver-wps-fork-t6x/src/wps'
(cd lwe && make BUILD_STATIC=y libiw.a)
make[1]: Entering directory '/home/soxrok2212/reaver-wps-fork-t6x/src/lwe'
make[1]: 'libiw.a' is up to date.
make[1]: Leaving directory '/home/soxrok2212/reaver-wps-fork-t6x/src/lwe'
(cd libwps && make)
make[1]: Entering directory '/home/soxrok2212/reaver-wps-fork-t6x/src/libwps'
make[1]: 'libwps.o' is up to date.
make[1]: Leaving directory '/home/soxrok2212/reaver-wps-fork-t6x/src/libwps'
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps wpsmon.c *.o libwps/*.o wps/*.o tls/bignum.o tls/libtls.a utils/libutils.a crypto/libcrypto.a lwe/libiw.a -ldl -lm -lpcap -lsqlite3  -o wash
gcc -DCONF_DIR='"/usr/local/etc/reaver"' -DREAVER_DATABASE='"/usr/local/etc/reaver/reaver.db"' -Wall -g -O2 -Ilibwps wpscrack.c *.o libwps/*.o wps/*.o tls/bignum.o tls/libtls.a utils/libutils.a crypto/libcrypto.a lwe/libiw.a -ldl -lm -lpcap -lsqlite3  -o reaver
`

**Comment by kcdtv** [comment]
okay okay  :smile_cat: 
  Doing things fast at coffee break is never a good idea.
I tried your "fixes" branch
` git clone -b fixes https://github.com/rofl0r/reaver-wps-fork-t6x.git`
And yes, you took away a bunch of warnings and there are no more warnings related to zao algorithm. 
Thanks for asll your efforts, I will speak very soon with soxrick2212 and we will probably merge your request if for him it is okay (for me it is) 
A bit ate here now, like 2 am, i hope we speak soon and maybe go further in this war against warnings
Take care!

**Comment by kcdtv** [comment]
Closing an issue was a wrong click mistake... it is late, i get out form here before i break something :laughing:

**Comment by rofl0r** [comment]
:)

you said
> war against warnings

and i want to emphasize that these (or at least most of them) were not "just warnings" but real issues. for example the missing declaration for "mac2str" caused the resulting pointer from that function being truncated to 32bit (i.e. the top 32bit lost), so any later usage of that pointer if it happened to point past the first 32bit of address space would cause a crash.

**Comment by soxrok2212** [comment]
Merged. Thank you!

**Comment by rofl0r** [comment]
thanks, now i can prepare a branch for my new feature (wash showing *all* APs, not just the WPS ones)

**Comment by kcdtv** [comment]
Guys.... They are stills a lot of warning
 You are probaly using kali in live mode and compiling from root account directly. 
If you are form a non rot account and compile you see a lot of warnings...
  Check what happenj when you compile from your root account with the tagg -Wall that explicit all warnings...
`(sudo) make -Wall`
And you will get a different stdout...
errors are here

> In file included from bignum.c:21:0:
libtommath.c: In function ‘mp_exptmod’:
libtommath.c:580:9: warning: variable ‘dr’ set but not used [-Wunused-but-set-variable]
     int dr;
         ^~
tlsv1_server_read.c: In function ‘tls_process_client_key_exchange_rsa’:
tlsv1_server_read.c:474:9: warning: variable ‘encr_len’ set but not used [-Wunused-but-set-variable]
     u16 encr_len;
         ^~~~~~~~
In file included from ../utils/common.h:18:0,
                 from md5-internal.c:17:
md5-internal.c: In function ‘MD5Final’:
md5-internal.c:191:29: warning: argument to ‘sizeof’ in ‘memset’ call is the same expression as the destination; did you mean to dereference it? [-Wsizeof-pointer-memaccess]
     os_memset(ctx, 0, sizeof(ctx)); /* In case it's sensitive */
                             ^
../utils/os.h:413:41: note: in definition of macro ‘os_memset’
 #define os_memset(s, c, n) memset(s, c, n)
                                         ^
wps_dev_attr.c: In function ‘wps_process_serial_number’:
wps_dev_attr.c:345:86: warning: passing argument 2 of ‘pingen_belkin’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 n] Pin Generated : %08d\n",pingen_belkin(mac2str(get_bssid(),'\0'), str, str_len, 0));
                                                                     ^~~
In file included from ../wps.h:40:0,
                 from ../defs.h:46,
                 from ../globule.h:38,
                 from wps_dev_attr.c:15:
../utils/common.h:447:5: note: expected ‘char *’ but argument is of type ‘const u8 * {aka const unsigned char *}’
 int pingen_belkin(char *mac, char *serial, int len_serial, int add);
     ^~~~~~~~~~~~~
wps_dev_attr.c:346:90: warning: passing argument 2 of ‘pingen_belkin’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 in Generated (+1): %08d\n",pingen_belkin(mac2str(get_bssid(),'\0'), str, str_len, 1));
                                                                     ^~~
In file included from ../wps.h:40:0,
                 from ../defs.h:46,
                 from ../globule.h:38,
                 from wps_dev_attr.c:15:
../utils/common.h:447:5: note: expected ‘char *’ but argument is of type ‘const u8 * {aka const unsigned char *}’
 int pingen_belkin(char *mac, char *serial, int len_serial, int add);
     ^~~~~~~~~~~~~
wps_dev_attr.c:347:92: warning: passing argument 2 of ‘pingen_belkin’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  Generated (-1): %08d\n\n",pingen_belkin(mac2str(get_bssid(),'\0'), str, str_len, -1));
                                                                     ^~~
In file included from ../wps.h:40:0,
                 from ../defs.h:46,
                 from ../globule.h:38,
                 from wps_dev_attr.c:15:
../utils/common.h:447:5: note: expected ‘char *’ but argument is of type ‘const u8 * {aka const unsigned char *}’
 int pingen_belkin(char *mac, char *serial, int len_serial, int add);
     ^~~~~~~~~~~~~
wps_registrar.c: In function ‘wps_process_ap_settings_r’:
wps_registrar.c:2791:27: warning: pointer targets in passing argument 1 of ‘strdup’ differ in signedness [-Wpointer-sign]
         wps->key = strdup(wps->cred.key);
                           ^~~
In file included from ../defs.h:42:0,
                 from ../globule.h:38,
                 from wps_registrar.c:14:
/usr/include/string.h:171:14: note: expected ‘const char *’ but argument is of type ‘u8 * {aka unsigned char *}’
 extern char *strdup (const char *__s)
              ^~~~~~
wps_registrar.c:2795:29: warning: pointer targets in passing argument 1 of ‘strdup’ differ in signedness [-Wpointer-sign]
         wps->essid = strdup(wps->cred.ssid);
                             ^~~
In file included from ../defs.h:42:0,
                 from ../globule.h:38,
                 from wps_registrar.c:14:
/usr/include/string.h:171:14: note: expected ‘const char *’ but argument is of type ‘u8 * {aka unsigned char *}’
 extern char *strdup (const char *__s)
              ^~~~~~
At top level:
wps_registrar.c:2252:12: warning: ‘wps_process_e_snonce2’ defined but not used [-Wunused-function]
 static int wps_process_e_snonce2(struct wps_data *wps, const u8 *e_snonce2)
            ^~~~~~~~~~~~~~~~~~~~~
wps_registrar.c:1456:24: warning: ‘wps_build_m2d’ defined but not used [-Wunused-function]
 static struct wpabuf * wps_build_m2d(struct wps_data *wps)
                        ^~~~~~~~~~~~~
wps_registrar.c:888:13: warning: ‘wps_cb_reg_success’ defined but not used [-Wunused-function]
 static void wps_cb_reg_success(struct wps_registrar *reg, const u8 *mac_addr,
             ^~~~~~~~~~~~~~~~~~
wps_registrar.c:862:12: warning: ‘wps_cb_new_psk’ defined but not used [-Wunused-function]
 static int wps_cb_new_psk(struct wps_registrar *reg, const u8 *mac_addr,
            ^~~~~~~~~~~~~~
wps_registrar.c:770:13: warning: ‘wps_registrar_pin_completed’ defined but not used [-Wunused-function]
 static void wps_registrar_pin_completed(struct wps_registrar *reg)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
wps_registrar.c:759:13: warning: ‘wps_registrar_pbc_completed’ defined but not used [-Wunused-function]
 static void wps_registrar_pbc_completed(struct wps_registrar *reg)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
wps_registrar.c:257:13: warning: ‘wps_registrar_remove_pbc_session’ defined but not used [-Wunused-function]
 static void wps_registrar_remove_pbc_session(struct wps_registrar *reg,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.c: In function ‘print_iface_version_info’:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:387:8: note: called from here
     if(iw_get_ext(skfd, ifname, SIOCGIWNAME, &wrq) < 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:396:8: note: called from here
     if(iw_get_ext(skfd, ifname, SIOCGIWRANGE, &wrq) < 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.c: In function ‘iw_get_range_info’:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:483:8: note: called from here
     if(iw_get_ext(skfd, ifname, SIOCGIWRANGE, &wrq) < 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.c: In function ‘iw_get_priv_info’:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:623:12: note: called from here
         if(iw_get_ext(skfd, ifname, SIOCGIWPRIV, &wrq) >= 0)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.c: In function ‘iw_set_basic_config’:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:748:8: note: called from here
     if(iw_get_ext(skfd, ifname, SIOCGIWNAME, &wrq) < 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:761:12: note: called from here
         if(iw_get_ext(skfd, ifname, SIOCSIWMODE, &wrq) < 0)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:506:9: warning: inlining failed in call to ‘iw_set_ext’: call is unlikely and code size would grow [-Winline]
         iw_set_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:773:12: note: called from here
         if(iw_set_ext(skfd, ifname, SIOCSIWFREQ, &wrq) < 0)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:506:9: warning: inlining failed in call to ‘iw_set_ext’: call is unlikely and code size would grow [-Winline]
         iw_set_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:793:16: note: called from here
             if(iw_set_ext(skfd, ifname, SIOCSIWENCODE, &wrq) < 0)
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:506:9: warning: inlining failed in call to ‘iw_set_ext’: call is unlikely and code size would grow [-Winline]
         iw_set_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:813:12: note: called from here
         if(iw_set_ext(skfd, ifname, SIOCSIWENCODE, &wrq) < 0)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:506:9: warning: inlining failed in call to ‘iw_set_ext’: call is unlikely and code size would grow [-Winline]
         iw_set_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:827:12: note: called from here
         if(iw_set_ext(skfd, ifname, SIOCSIWNWID, &wrq) < 0)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:506:9: warning: inlining failed in call to ‘iw_set_ext’: call is unlikely and code size would grow [-Winline]
         iw_set_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:850:12: note: called from here
         if(iw_set_ext(skfd, ifname, SIOCSIWESSID, &wrq) < 0)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.c: In function ‘iw_get_basic_config’:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:673:8: note: called from here
     if(iw_get_ext(skfd, ifname, SIOCGIWNAME, &wrq) < 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:683:8: note: called from here
     if(iw_get_ext(skfd, ifname, SIOCGIWNWID, &wrq) >= 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:690:8: note: called from here
     if(iw_get_ext(skfd, ifname, SIOCGIWFREQ, &wrq) >= 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:701:8: note: called from here
     if(iw_get_ext(skfd, ifname, SIOCGIWENCODE, &wrq) >= 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:712:8: note: called from here
     if(iw_get_ext(skfd, ifname, SIOCGIWESSID, &wrq) >= 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:719:8: note: called from here
     if(iw_get_ext(skfd, ifname, SIOCGIWMODE, &wrq) >= 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.c: In function ‘iw_get_stats’:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:1276:12: note: called from here
         if(iw_get_ext(skfd, ifname, SIOCGIWSTATS, &wrq) < 0)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.c: In function ‘iw_process_scan’:
iwlib.h:506:9: warning: inlining failed in call to ‘iw_set_ext’: call is unlikely and code size would grow [-Winline]
         iw_set_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:3058:13: note: called from here
         if((iw_set_ext(skfd, ifname, SIOCSIWSCAN, &wrq) < 0)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from iwlib.c:14:0:
iwlib.h:522:9: warning: inlining failed in call to ‘iw_get_ext’: call is unlikely and code size would grow [-Winline]
         iw_get_ext(int   skfd,  /* Socket to the kernel */
         ^~~~~~~~~~
iwlib.c:3082:8: note: called from here
     if(iw_get_ext(skfd, ifname, SIOCGIWSCAN, &wrq) < 0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ar: `u' modifier ignored since `D' is the default (see `U')
libwps.c: In function ‘parse_wps_parameters’:
libwps.c:29:12: warning: variable ‘data_len’ set but not used [-Wunused-but-set-variable]
     size_t data_len = 0, offset = 0;
            ^~~~~~~~


> thanks, now i can prepare a branch for my new feature (wash showing all APs, not just the WPS ones)


 I would personally use airodump-ng with -wps tag for that
 The advantage of mot showing all PA is that stdout is smaller and much easier to handle than if you show all PA 
  May I suggest you to make it optional with an extra argument (not enabled by default).

**Comment by rofl0r** [comment]
most of these warnings are not really important (like unused functions or variables), so i didn't touch them, but i'm gonna fix a few of em now in another PR.

**Comment by kcdtv** [comment]
Cool! :sunglasses: 
No hurry: it has been full of them for ages...
 Thanks again for your contributions.

**Pull request merged**
