### PR TITLE
Add OS X support

### PR DESCRIPTION
**Pull request by alex-chan**
Add OS X support for compile
diff file takes from :https://docs.google.com/file/d/0B3tHnfnS08GyVUNSNFl5bHdEN1k/edit

### CODE REVIEW

**Comment by t6x** [comment]
hello

I'm having some problems with the automatic merge.

There are some things I did and still not put in git, then this occurring some conflicts.

So I will do the merge manually when I finish some things.


Thank you for that modification to support OS X.


Thank you very much.

**Comment by t6x** [comment]
If you want I can add you as a collaborator for you to make updates directly if needed.

**Comment by alex-chan** [comment]
OK. I can merge it myself.
BTW: about the test , I simply tested on my own OS X 10.10 and succeed. I don't know what other test to do.
What do you mean by "I will ask for the Sox do the necessary tests there then do the merge." ?

**Comment by t6x** [comment]
translation was wrong.

I'm using the google translate and it always confuses and translation comes out very bad.

Sorry about that.

**Comment by karatewaffles** [comment]
hello.
thank you very much for all your hard work.
i've been running reaver 1.4 on OS X and recently running the newer version with pixiewps in linux.
i'd love to update my OS X version to 1.5.2 (though i realise it isn't fully supported and is originally for linux). i grabbed the 1.5.2 fork and did a ./config - make - make install. the first two steps only produced one minor-looking error, but the make install didn't do anything other than configure some folders.
i found this .diff file referencing OS X support and i'm trying to research how to actually apply the patch.

when i run "patch < reaver_osx.diff" i get a load of "Hunk #x FAILED" errors.
i'd just like to learn what i'm doing wrong and how to fix it.

i've place the .diff file in the /src directory before running config and make. i've also tried config first then patching, as well as config then make then patching, but the results are so far the same.

thank you for any further information.

**Comment by crushedice2000** [comment]
@karatewaffles: I haven't done any hard work yet, only proposed the format
of the database, about the OS X problem, I think you should open a new
issue for that. This will contribute to keep the issues page clear and
structured. Also I don't know nothing of OS X.

Did you try the latest code?

When you open the new issue, please put the code or compilation output
formatted as markdown code (prepending 4 spaces to each line), look this
code example:

    Line 1
    Line 2
    Line 3

How I got it:

        Line 1
        Line 2
        Line 3

**Comment by karatewaffles** [comment]
thanks for your response.
i saw another ticket regarding os x support that was closed with everyone
saying that reaver doesn't support anything but linux.
i was (and am) confused by that, as the file list page shows several files
with notes next to them saying "Added OS X support".

at any rate, what should i do with the .diff file apart from what i've
already tried?

i'll try opening another ticket regarding OS X and see if it doesn't get
shut down again.
and i'll be sure to format my notes.

many thanks.

**Comment by alex-chan** [comment]
Hello @karatewaffles , this version of reaver has merged the OSX patch, so you needn't merge yourself. Just grab it , compile it , install it. 

Well, It at least work fine on my mac (OX 10.10.4)

**Comment by karatewaffles** [comment]
okay thanks, that's what i was beginning to suspect.

hasn't worked for me so far in 10.9.4 with macports yet, but i'll keep
trying.
the old version of reaver still works great, but i'd love to get pixiewps
incorporated working, or at the very least be able to view the M2 packet.

thanks again for your help.

**Pull request merged**
