### PR TITLE
Replace obsolete ualarm, setitimer with timer_settime

### PR DESCRIPTION
**Pull request by feitoi**
Continue the PR #330

### CODE REVIEW

**Comment by rofl0r** [comment]
anyone up for testing this, @drygdryg for example ?

**Comment by drygdryg** [comment]
Built successfully in Termux on Android 12 using Clang 14.0.6 (Bionic libc).

**Comment by rofl0r** [comment]
cool, does it also work as intended ?

**Comment by drygdryg** [comment]
> Compiled successfully in Termux on Android 12 using Clang 14.0.6 (Bionic libc).

Just tested Wash and Reaver on this device, works fine. Used TP-LINK TL-WN722N v2 external USB Wi-Fi adapter  (Realtek RTL8188EU) with [the driver from the aircrack-ng project](https://github.com/aircrack-ng/rtl8188eus). Kernel version: 4.9.266, Android version: 12.

**Pull request merged**
