### PR TITLE
fix-memory-corruption(#88), and better way to copy

### PR DESCRIPTION
**Pull request by xhebox**
following #88

### CODE REVIEW

**Comment by YI1992** [comment]
xhebox,太感谢了，打了上个版本的补丁，reaver在路由器上后台正常运行了大约6小时30分钟，手动终止后更换第二版本补丁，正在pin.

**Comment by xhebox** [comment]
@YI1992 国人？嘛，帮上忙就好，openwrt现在全换musl了？uclibc应该不会有问题的吧。另外，交朋友吗? :smiley:

**Comment by YI1992** [comment]
哈哈，你太客气了。我在用LEDE，uclibc我以后编译个CC版测试吧

**Comment by YI1992** [comment]
第二版补丁运行了3小时，正常，未出现segmentation fault。

**Comment by xhebox** [comment]
@YI1992 两版补丁都是一样的，区别只是第二个补全了git版本新加的一个地方（那个地方是给mac用的）
Two editions are the same, except that the second one add a fix for mac(which is not added in 1.5.2, but git), too.

**Comment by YI1992** [comment]
我编译的正是git版本70f6b92a8d455eb8d9dfedf7a71256e172d5b5e8提交，打了大小端补丁，大端CPU运行的很好。

**Comment by kcdtv** [comment]
Hi there!
Many thanks for your contribution!
Could you use English please? :smiley_cat:  
It is not my language neither, but you know, we all have to make effort to communicate. 
As far as i understand the value of BUFSIZ depend on every platform.
What is the advantage to use a generic static value?  
BIFSIZ maixmum anyway isn't it 64 kb?

**Comment by xhebox** [comment]
@kcdtv Sorry for that, i'll give a translation next time. This should get macos fixed, too. :+1:

**Pull request merged**
