### PR TITLE
Fix -n argument

### PR DESCRIPTION
**Pull request by vk496**

### CODE REVIEW

**Comment by soxrok2212** [comment]
I have not had a problem with the -n argument so I will wait until the community is able to test and I have sufficient reports of success or success from a reputable source. Thank you!

**Comment by vk496** [comment]
Some fixes for compiler warnings. #52

**Comment by wifislax-ng** [comment]
when use argument  -g +  -p  = nonstop

if put

reaver -c XX -i XXX -b xx:xx:xx:xx:xx:xx -g 1 -p XXXXXXX -n -vv

no stop after try 1 attemp of a direct pin.

patch by vk496 fix this issue.

-g argumenten is nice when try only 1 attemp of a single pin ...  for non BLOCK WPS.

This are break since months.

**Comment by kcdtv** [comment]
Hi guys!
  Thanks for all your effort.
Could you test the mod' against an acess point that requires -n argument in order to get the WPA passphrase? I do not have one and cannot check it. 
_¡Saludos!
Gracias para todo 
¿Se ha podido comprobar contra un PA que requiere el argumento -n para obtener la contraseña WPA?
 Desgraciadamente no tengo ninguno para comprobarlo._

**Pull request closed without merging**
