### PR TITLE
Added MAC changer functionality from old fork of reaver.

### PR DESCRIPTION
**Pull request by adde88**
This was mentioned in issue #331 from @elleven11
So i took the liberty of porting the changes from this old fork: https://github.com/gabrielrcouto/reaver-wps

### CODE REVIEW

**Comment by rofl0r** [comment]
thanks for your effort, though in its current form i can't merge this. this PR changes a **lot** more than simply adding the functionality. i  can't actually see the changes needed for the mac-changer functionality or whether new functionality has been thrown out (i.e. the code from the other repo simply copied over this repo).
it starts with 300 changed lines in README. is it only whitespace changes? or did you change formatting to your own liking? i can't tell.
there's a good reason i asked to first to get a diff between vanilla 1.4 and that other repo, so one can actually see what was changed. also the VERSION is only ever changed when a release is published, and i reserve that right for myself.

**Comment by adde88** [comment]
Wow, thanks for the heads-up. Something seems to have gone haywire here. I'm not sure exactly what happened.
But i'll be sure to fix it. It wasn't nearly that much changes that needed to be done!

I actually did perform a diff of reaver v1.4 and the fork with the MAC changes as you suggested, and then used that diff to manually add the changes needed to the master branch.
The only other changes i made was to the README, where i added some stuff that was missing.

Regarding the diff, i'll add it here if you're interested in reading it. :)

[reaver-1.4-vs-mac-fork.diff.txt](https://github.com/t6x/reaver-wps-fork-t6x/files/5982183/reaver-1.4-vs-mac-fork.diff.txt)

**Comment by adde88** [comment]
I've fixed the whitespace/formatting issue you brought to my attention.
If you want me to reopen this PR, please say so. :)

You can see the correct changes i made here: https://github.com/t6x/reaver-wps-fork-t6x/compare/master...adde88:master

**Comment by rofl0r** [comment]
for the record i'm attaching the diff here inline:

```diff
diff --git a/src/argsparser.c b/src/argsparser.c
index a61efb8..44dd514 100644
--- a/src/argsparser.c
+++ b/src/argsparser.c
@@ -41,7 +41,7 @@ int process_arguments(int argc, char **argv)
 	int long_opt_index = 0;
 	char bssid[MAC_ADDR_LEN] = { 0 };
 	char mac[MAC_ADDR_LEN] = { 0 };
-	char *short_options = "b:e:m:i:t:d:c:T:x:r:g:l:o:p:s:C:aA5ELfnqvDShwN";
+	char *short_options = "b:e:m:i:t:d:c:T:x:r:g:l:o:p:s:C:aA5ELfnqvDShwNM";
 	struct option long_options[] = {
 		{ "interface", required_argument, NULL, 'i' },
 		{ "bssid", required_argument, NULL, 'b' },
		
		
@@ -73,6 +73,7 @@ int process_arguments(int argc, char **argv)
 		{ "verbose", no_argument, NULL, 'v' },
 		{ "win7", no_argument, NULL, 'w' },
 		{ "help", no_argument, NULL, 'h' },
+		{ "mac-changer", no_argument, NULL, 'M' },
 		{ 0, 0, 0, 0 }
 	};
 
 
 
@@ -173,6 +174,9 @@ int process_arguments(int argc, char **argv)
 			case 'N':
 				set_oo_send_nack(0);
 				break;
+			case 'M':
+				set_mac_changer(1);
+				break;
                         default:
                                 ret_val = EXIT_FAILURE;
                 }
				 
				 
@@ -198,6 +202,7 @@ void init_default_settings(void)
         set_timeout_is_nack(1);
 	set_oo_send_nack(1);
         set_wifi_band(BG_BAND);
+	set_mac_changer(0);
 }
 
 /* Parses the recurring delay optarg */
 
 
diff --git a/src/cracker.c b/src/cracker.c
index a07caa6..2f26a1b 100644
--- a/src/cracker.c
+++ b/src/cracker.c
@@ -42,6 +42,12 @@ void crack()
 	float pin_count = 0;
 	time_t start_time = 0;
 	enum wps_result result = 0;
+	/* MAC CHANGER VARIABLES */	
+	int mac_changer_counter = 0;
+	char mac[MAC_ADDR_LEN] = { 0 };
+	unsigned char mac_string [] = "ZZ:ZZ:ZZ:ZZ:ZZ:ZZ";
+	unsigned char* new_mac = &mac_string[0];
+	char last_digit = '0';
 
 	if(!get_iface())
 	{
	
	
@@ -117,9 +123,78 @@ void crack()
 			set_key_status(KEY2_WIP);
 		}
 
+		//copy the current mac to the new_mac variable for mac changer
+		if (get_mac_changer() == 1) {
+			strncpy(new_mac, mac2str(get_mac(), ':'), 16);
+		}
+
 		/* Main cracking loop */
 		for(loop_count=0, sleep_count=0; get_key_status() != KEY_DONE; loop_count++, sleep_count++)
 		{
+			//MAC Changer switch/case to define the last mac address digit
+			if (get_mac_changer() == 1) {			
+				switch (mac_changer_counter) {
+					case 0:
+					last_digit = '0';
+					break;
+					case 1:
+					last_digit = '1';
+					break;
+					case 2:
+					last_digit = '2';
+					break;
+					case 3:
+					last_digit = '3';
+					break;
+					case 4:
+					last_digit = '4';
+					break;
+					case 5:
+					last_digit = '5';
+					break;
+					case 6:
+					last_digit = '6';
+					break;
+					case 7:
+					last_digit = '7';
+					break;
+					case 8:
+					last_digit = '8';
+					break;
+					case 9:
+					last_digit = '9';
+					break;
+					case 10:
+					last_digit = 'A';
+					break;
+					case 11:
+					last_digit = 'B';
+					break;
+					case 12:
+					last_digit = 'C';
+					break;
+					case 13:
+					last_digit = 'D';
+					break;
+					case 14:
+					last_digit = 'E';
+					break;
+					case 15:
+					last_digit = 'F';
+					mac_changer_counter = -1;
+					break;
+				}
+
+				mac_changer_counter++;
+
+				new_mac[16] = last_digit;
+				//transform the string to a MAC and define the MAC
+				str2mac((unsigned char *) new_mac, (unsigned char *) &mac);
+				set_mac((unsigned char *) &mac);
+			
+				cprintf(WARNING, "[+] Using MAC %s \n", mac2str(get_mac(), ':'));
+			}			
+			
 			/* 
 			 * Some APs may do brute force detection, or might not be able to handle an onslaught of WPS
 			 * registrar requests. Using a delay here can help prevent the AP from locking us out.
			 
			 
			 
diff --git a/src/globule.c b/src/globule.c
index 1409387..ea6a17f 100644
--- a/src/globule.c
+++ b/src/globule.c
@@ -578,3 +578,12 @@ int get_oo_send_nack(void)
 {
 	return globule->oo_send_nack;
 }
+
+void set_mac_changer(int value)
+{
+	globule->mac_changer = value;
+}
+int get_mac_changer()
+{
+	return globule->mac_changer;
+}



diff --git a/src/globule.h b/src/globule.h
index 7529940..5fd6e2f 100644
--- a/src/globule.h
+++ b/src/globule.h
@@ -138,6 +138,8 @@ struct globals
 					 * wpa_supplicant's wps_data structure, needed for almost all wpa_supplicant
                                          * function calls.
                                          */
+	int mac_changer;		/* Use MAC changer */
+
 } *globule;
 
 int globule_init();
 
 
@@ -239,4 +241,7 @@ char *get_exec_string(void);
 void set_oo_send_nack(int value);
 int get_oo_send_nack(void);
 
+void set_mac_changer(int value);
+int get_mac_changer(void);
+
 #endif
diff --git a/src/wpscrack.c b/src/wpscrack.c
index ebd71d0..34a75aa 100644
--- a/src/wpscrack.c
+++ b/src/wpscrack.c
@@ -176,6 +176,7 @@ int usage(char *prog_name)
         fprintf(stderr, "\t-E, --eap-terminate             Terminate each WPS session with an EAP FAIL packet\n");
         fprintf(stderr, "\t-n, --nack                      Target AP always sends a NACK [Auto]\n");
 	fprintf(stderr, "\t-w, --win7                      Mimic a Windows 7 registrar [False]\n");
+	fprintf(stderr, "\t-M, --mac-changer               Change the last digit of the MAC Address for each pin try [False]\n");
 
         fprintf(stderr, "\nExample:\n\t%s -i mon0 -b 00:90:4C:C1:AC:21 -vv\n\n", prog_name);
 
```
note that the 2 routines get_mac() and set_mac() are missing here, probably they were added to a new .c file.

**Comment by rofl0r** [comment]
i gave this another look re set_mac() and get_mac() and found they're already in reaver, however unlike i expected they don't actually change the mac of the interface, just what reaver *thinks* the mac is. which in turn made me realize that since we're working in *monitor* mode, we can use *any* mac address even if it's not corresponding to the interface. this would allow us to even get rid of the platform-specific code in src/iface.c and always use a random mac to begin with. anyway, feel free to reopen the PR since it should work. the mac_changer switch statement code is quite lame but we can address that later.

**Pull request closed without merging**
