### PR TITLE
Nosqlite

### PR DESCRIPTION
**Pull request by rofl0r**
got rid of sqlite entirely.
the only functionality that needed to be removed is the -a (i.e. scripkiddie) flag.

### CODE REVIEW

**Comment by soxrok2212** [comment]
Nice work :)

**Comment by soxrok2212** [comment]
Actually, there is a small bug. It compiles fine but running make install results in this.
'rm -f /usr/local/bin/reaver /usr/local/bin/wash /usr/local/bin/walsh
if [ ! -d /usr/local/etc/reaver ]; then mkdir -p /usr/local/etc/reaver; fi
if [ ! -e /usr/local/etc/reaver/reaver.db ]; then cp reaver.db /usr/local/etc/reaver/reaver.db && chmod -R a+rw /usr/local/etc/reaver; fi
cp: cannot stat ‘reaver.db’: No such file or directory
Makefile:103: recipe for target 'install' failed
make: *** [install] Error 1
'

**Comment by soxrok2212** [comment]
Criticize me if you must, but removing the database configs in Makefile.in seems to resolve this issue... testing soon.

I removed these two lines and had a successful install.

>CFLAGS=-DCONF_DIR='"$(CONFDIR)"' -DREAVER_DATABASE='"$(CONFDIR)/reaver.db"' @CFLAGS@ -Wno-unused-function

>	if [ ! -e $(CONFDIR)/reaver.db ]; then cp reaver.db $(CONFDIR)/reaver.db && chmod -R a+rw $(CONFDIR); fi

**Comment by rofl0r** [comment]
oh indeed, you're right
i didn't test `make install`. can you push your change ?

**Comment by rofl0r** [comment]
actually, just the line copying reaver.db

**Comment by rofl0r** [comment]
ok, please wait with that, i'll commit a proper fix

**Pull request merged**
